### ISSUE TITLE
Failed to start connection: Error: failed to retrieve port from stream

### ISSUE THREAD

**Issue by djarami726** [MuhammedKalkan/OpenLens#123] opened 2023-02-02 16:16 UTC
Describe the bug
One of my collegues is trying to setup openlens and gets the following error when connecting to the AKS cluster.
Failed to start connection: Error: failed to retrieve port from stream

To Reproduce

Start OpenLens
Click on catalog
See error
Kubectl works fine from the terminal against that cluster. I'm able to do the following without a problem:
Kubectl get pods -A
Kubectl get ns -A

Expected behavior
The cluster should open up. I have installed it on another machine same version and os and it works fine.

Screenshots
![image](https://user-images.githubusercontent.com/107571134/216380050-e144156c-53a7-43dd-864d-eb654e19ed33.png)

Environment (please complete the following information):

Lens Version: 6.4.0-beta.10
OS: Windows 11
Download exe and install
Logs:
When you run the application executable from command line you will see some logging output. Please paste them here:

didn't see any console logs

**Comment by Happin3ss** [comment] 2023-02-02 18:19
I got the same issue with beta.9 on Windows 10. I have tried to uninstall + delete OpenLens in Appdata\Roaming and Appdata\Local then reinstall but the issue still happen
![image](https://user-images.githubusercontent.com/17236895/216411876-3ed05829-708a-42f2-9d34-50f1b6440bdc.png)

**Comment by avg07** [comment] 2023-02-03 10:09
I had the same issue. Solved by adding the binary from [here](https://github.com/lensapp/lens-k8s-proxy/releases) to AppData\Local\Programs\OpenLens\resources\x64\

**Comment by Happin3ss** [comment] 2023-02-03 10:16
> I had the same issue. Solved by adding the binary from [here](https://github.com/lensapp/lens-k8s-proxy/releases) to AppData\Local\Programs\OpenLens\resources\x64\

Nice ! I can confirm this works ! 
For me I installed OpenLens for all users so it would look like this in the end
![image](https://user-images.githubusercontent.com/17236895/216574497-e3bbc7f2-3c17-40b1-822d-0fe7ffc3bc92.png)

**Comment by jkroepke** [comment] 2023-02-03 11:47
Duplicate of https://github.com/MuhammedKalkan/OpenLens/issues/109

**Closed by jkroepke** 2023-02-03 11:47 UTC
