### ISSUE TITLE
spawn installpath\resources\x64\lens-k8s-proxy.exe ENOENT

### ISSUE THREAD

**Issue by Mrchensama** [MuhammedKalkan/OpenLens#115] opened 2023-01-30 09:43 UTC
I just installed the lastest version `6.4.0-beta.9` and got error message like this:
![image](https://user-images.githubusercontent.com/40376729/215441219-66aa729f-cde8-453c-abd8-59517bfff2b9.png)
I searched the directory, and found that the directory `D:\OpenLens\resources\x64` does not exist 
After searching in settings, i did not find any config to solve this problem.

Anyone else get this error?

PC system is win11.

**Comment by bakito** [comment] 2023-01-30 10:02
I also have this error on Windows with version OpenLens-6.4.0-beta.9.exe

**Comment by jkroepke** [comment] 2023-01-30 13:51
Duplicate of #109

**Closed by jkroepke** 2023-01-30 13:51 UTC
